details:
  namespace: student10-bookinfo-prd
  image: ghcr.io/rungwarapon/bookinfo-details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081 
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.opsta.net
  path: "/student10/details(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  ENABLE_EXTERNAL_BOOK_SERVICE: "true"